project(
    WAGEDIT
    LANGUAGES C CXX
)

set(CMAKE_C_STANDARD 17)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

#file(GLOB_RECURSE CONFIGURE_DEPENDS WAGEDIT_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")

#add_executable(${PROJECT_NAME} ${CONFIGURE_DEPENDS})
#target_include_directories(${PROJECT_NAME} PUBLIC 
#    ${WAG_ENGINE_INCLUDE_DIR} 
#    ${CMAKE_CURRENT_SOURCE_DIR}/src 
#    ${CMAKE_CURRENT_SOURCE_DIR}/include
#)
#target_link_libraries(${PROJECT_NAME} WAG)
#target_compile_definitions(${PROJECT_NAME} PUBLIC 
#    WAG_ARCHITECTURE="${CMAKE_SYSTEM_PROCESSOR}"
#    WAG_PLATFORM="${CMAKE_SYSTEM_NAME}"
#    WAG_PLATFORM_VERSION="${CMAKE_SYSTEM_VERSION}"
#    WAG_COMPILE_DATE="${CMAKE_BUILD_TIMESTAMP}"
#    WAG_CXX_COMPILER="${CMAKE_CXX_COMPILER_ID}"
#    WAG_CXX_COMPILER_VERSION="${CMAKE_CXX_COMPILER_VERSION}"
#    WAG_C_COMPILER="${CMAKE_C_COMPILER_ID}"
#    WAG_C_COMPILER_VERSION="${CMAKE_C_COMPILER_VERSION}"
#    WAG_BUILD_TYPE="${CMAKE_BUILD_TYPE}"
#)